onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/clk
add wave -noupdate /tb_top/rst_n
add wave -noupdate /tb_top/clk_out
add wave -noupdate /tb_top/mosi_out
add wave -noupdate /tb_top/sel_out
add wave -noupdate /tb_top/miso_input
add wave -noupdate /tb_top/s14
add wave -noupdate /tb_top/s13
add wave -noupdate /tb_top/s12
add wave -noupdate /tb_top/uut/CLK
add wave -noupdate /tb_top/uut/RST_N
add wave -noupdate /tb_top/uut/miso_input
add wave -noupdate /tb_top/uut/clk_output
add wave -noupdate /tb_top/uut/mosi_output
add wave -noupdate /tb_top/uut/sel_output
add wave -noupdate /tb_top/uut/s14
add wave -noupdate /tb_top/uut/s13
add wave -noupdate /tb_top/uut/s12
add wave -noupdate /tb_top/uut/clk_pll
add wave -noupdate /tb_top/uut/clk_pll_continuous
add wave -noupdate /tb_top/uut/clk_continuous_slow
add wave -noupdate /tb_top/uut/clk_continuous_fast
add wave -noupdate /tb_top/uut/clk_out_slow
add wave -noupdate /tb_top/uut/clk_out_fast
add wave -noupdate /tb_top/uut/mosi
add wave -noupdate /tb_top/uut/mosi_slow
add wave -noupdate /tb_top/uut/mosi_fast
add wave -noupdate /tb_top/uut/aux_selection
add wave -noupdate /tb_top/uut/aux_selection_slow
add wave -noupdate /tb_top/uut/aux_selection_fast
add wave -noupdate /tb_top/uut/clk_output_aux
add wave -noupdate /tb_top/uut/mosi_output_aux
add wave -noupdate /tb_top/uut/sel_output_aux
add wave -noupdate /tb_top/uut/signal_sdo
add wave -noupdate /tb_top/uut/latch_input
add wave -noupdate /tb_top/uut/flag_signal
add wave -noupdate /tb_top/uut/DYNLATCH
add wave -noupdate /tb_top/uut/STATLATCH
add wave -noupdate -radix hexadecimal /tb_top/uut/DYNCNF
add wave -noupdate -radix hexadecimal /tb_top/uut/STATCNF
add wave -noupdate /tb_top/uut/flag_signal_out
add wave -noupdate /tb_top/uut/top_pll_inst/REFERENCECLK
add wave -noupdate /tb_top/uut/top_pll_inst/RESET
add wave -noupdate /tb_top/uut/top_pll_inst/PLLOUTCORE
add wave -noupdate /tb_top/uut/top_pll_inst/PLLOUTGLOBAL
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/REFERENCECLK
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/PLLOUTCORE
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/PLLOUTGLOBAL
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/EXTFEEDBACK
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/DYNAMICDELAY
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/LOCK
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/BYPASS
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/RESETB
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/LATCHINPUTVALUE
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/SDO
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/SDI
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/SCLK
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/SPLLOUT1net
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/SPLLOUT2net
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/REFERENCECLK
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/EXTFEEDBACK
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/DYNAMICDELAY
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/BYPASS
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/RESETB
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/PLLOUT1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/PLLOUT2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/LOCK
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/FSEnet
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/FBnet
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/finedelayFBin
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/finedelayFBout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/DIVFBus
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/DIVRBus
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/DIVQBus
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/RANGEBus
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/ABPLLOUT
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/pllout1Sel
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/pllout2Sel
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/delaymuxsel
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/ABPLLOUTDiv2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/phase0net
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/phase90net
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/pllout2Muxnet
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/pllout1Muxnet
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/fdaRelInput
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/clk
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/init
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/phase0
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/phase90
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/ff1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/ff2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/ff3
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/ff4
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/ff5
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/ff6
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instShftReg427/ff7
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFBDlyAdjInMux/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFBDlyAdjInMux/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFBDlyAdjInMux/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFBDlyAdjInMux/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFBDlyAdjInMux/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFBDlyAdjInMux/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT2SelMux/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT2SelMux/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT2SelMux/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT2SelMux/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT2SelMux/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT2SelMux/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT1SelMux/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT1SelMux/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT1SelMux/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT1SelMux/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT1SelMux/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instPLLOUT1SelMux/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/signalin
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/DlyAdj
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delayedout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/l2muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/fixed_delay_adj
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/bufcntselector
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufout1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/muxinvout1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufout2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/muxinvout2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufout3
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/muxinvout3
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufout4
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/muxinvout4
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/s
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/delay4bufout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/muxinvout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/buf1out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/buf2out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/buf3out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst1/muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/s
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/delay4bufout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/muxinvout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/buf1out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/buf2out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/buf3out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst2/muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/s
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/delay4bufout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/muxinvout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/buf1out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/buf2out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/buf3out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst3/muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/s
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/delay4bufout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/muxinvout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/buf1out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/buf2out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/buf3out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/delay4bufinst4/muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/level2muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/level2muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/level2muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/level2muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/level2muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjFB/level2muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/signalin
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/DlyAdj
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delayedout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/l2muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/fixed_delay_adj
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/bufcntselector
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufout1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/muxinvout1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufout2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/muxinvout2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufout3
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/muxinvout3
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufout4
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/muxinvout4
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/s
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/delay4bufout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/muxinvout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/buf1out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/buf2out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/buf3out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst1/muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/s
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/delay4bufout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/muxinvout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/buf1out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/buf2out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/buf3out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst2/muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/s
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/delay4bufout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/muxinvout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/buf1out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/buf2out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/buf3out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst3/muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/s
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/delay4bufout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/muxinvout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/buf1out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/buf2out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/buf3out
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/muxout
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/delay4bufinst4/muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/level2muxinst/a
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/level2muxinst/b
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/level2muxinst/c
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/level2muxinst/d
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/level2muxinst/select
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instFineDlyAdjRel/level2muxinst/o
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/REF
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/FB
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/FSE
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/BYPASS
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/RESET
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVF6
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVF5
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVF4
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVF3
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVF2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVF1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVF0
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVR3
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVR2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVR1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVR0
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVQ2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVQ1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/DIVQ0
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/RANGE2
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/RANGE1
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/RANGE0
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/LOCK
add wave -noupdate /tb_top/uut/top_pll_inst/top_pll_inst/genblk1/instSbtSPLL/instABitsPLL/PLLOUT
add wave -noupdate /tb_top/uut/divisor_inst/clk_in
add wave -noupdate /tb_top/uut/divisor_inst/RST_N
add wave -noupdate /tb_top/uut/divisor_inst/clk_out
add wave -noupdate /tb_top/uut/divisor_inst/counter
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/flag_input
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/flag_output
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/flag_input_reg
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_slow_original
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/RST_N
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/SEL
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/MOSI
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_7
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_2
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_3
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_4
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_5
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6b
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6c
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6d
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6e
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6f
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6g
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6h
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6i
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/CLK_uC_6j
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/counter_idle
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/counter_din
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/counter_stat
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/current_state
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/next_state
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/bit_sequence_din
add wave -noupdate /tb_top/uut/FSM_TEST_inst_RAPIDA/bit_sequence_stat
add wave -noupdate /tb_top/uut/divisor_inst_2/clk_in
add wave -noupdate /tb_top/uut/divisor_inst_2/RST_N
add wave -noupdate /tb_top/uut/divisor_inst_2/clk_out
add wave -noupdate /tb_top/uut/divisor_inst_2/counter
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/flag_input
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/flag_input_reg
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_slow_original
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/RST_N
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/SEL
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/MOSI
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_7
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_2
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_3
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_4
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_5
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6b
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6c
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6d
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6e
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6f
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6g
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6h
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6i
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6j
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6k
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6l
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6m
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6n
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6o
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6p
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6q
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6r
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6s
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6t
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6u
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6v
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6w
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6x
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6y
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/CLK_uC_6z
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/counter_idle
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/counter_din
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/counter_stat
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/current_state
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/next_state
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/bit_sequence_din
add wave -noupdate /tb_top/uut/FSM_TEST_inst_slow/bit_sequence_stat
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/CLK
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/RST_N
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/SEL
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/SDI
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/SDO
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/STATCNF
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/STATSR
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/DYNCNF
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/DYNSR
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/AMUXSEL
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/STG2_EN
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/STG1_EN
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/ref_elec_en
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/STATDEF
add wave -noupdate /tb_top/uut/config_register_latched_dec_inst/DYNDEF
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {200620325 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 297
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {185656479 ps} {224886845 ps}
